steps:
  - name: node:14
    entrypoint: npm
    args: [ "ci" ]
  - name: node:14
    entrypoint: npm
    args: [ "run", "build" ]
  - name: "gcr.io/cloud-builders/gcloud"
    args: [ "app", "deploy" ]
timeout: "1600s"